version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install:
          install-yarn: true 
workflows:
    example-workflow:
      jobs:
        - node/test:
            run-command: test 